### PR TITLE
fix: generate a file per resourcePool

### LINKED ISSUE #576: CDI: two sriovnodepolicy configs(8 vfs) but only four deviceNode
### What happened?

I have two sriovnodepolicy configs, see below:

```
root@controller-node-1:/home/cyclinder/sriov# kubectl get sriovnetworknodepolicies.sriovnetwork.openshift.io -A -o wide
NAMESPACE     NAME      AGE
kube-system   policy1   43m
kube-system   policy2   7m44s
```

```
root@controller-node-1:/home/cyclinder/sriov# kubectl get sriovnetworknodestates.sriovnetwork.openshift.io -n kube-system -o yaml
apiVersion: v1
items:
- apiVersion: sriovnetwork.openshift.io/v1
  kind: SriovNetworkNodeState
  metadata:
    annotations:
      sriovnetwork.openshift.io/current-state: Idle
      sriovnetwork.openshift.io/desired-state: Idle
    creationTimestamp: "2024-07-16T03:50:05Z"
    generation: 5
    name: worker-node-1
    namespace: kube-system
    ownerReferences:
    - apiVersion: sriovnetwork.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: SriovOperatorConfig
      name: default
      uid: 2427ae73-ef95-4f57-aa85-c681ff9a48bb
    resourceVersion: "40147316"
    uid: 67f59ed6-85a3-4913-a1bf-3697dd008310
  spec:
    interfaces:
    - name: enp4s0f0np0
      numVfs: 4
      pciAddress: "0000:04:00.0"
      vfGroups:
      - isRdma: true
        policyName: policy1
        resourceName: rdma_resource
        vfRange: 0-3
    - name: enp4s0f1np1
      numVfs: 4
      pciAddress: "0000:04:00.1"
      vfGroups:
      - isRdma: true
        policyName: policy2
        resourceName: rdma_resource1
        vfRange: 0-3
  status:
    interfaces:
    - Vfs:
      - deviceID: "1018"
        driver: mlx5_core
        mac: e6:bc:60:22:14:6c
        mtu: 1500
        name: enp4s0f0v0
        pciAddress: "0000:04:00.2"
        vendor: 15b3
        vfID: 0
      - deviceID: "1018"
        driver: mlx5_core
        mac: a2:d7:89:ad:5d:b7
        mtu: 1500
        name: enp4s0f0v1
        pciAddress: "0000:04:00.3"
        vendor: 15b3
        vfID: 1
      - deviceID: "1018"
        driver: mlx5_core
        mac: d2:0b:3f:c9:ab:a4
        mtu: 1500
        name: enp4s0f0v2
        pciAddress: "0000:04:00.4"
        vendor: 15b3
        vfID: 2
      - deviceID: "1018"
        driver: mlx5_core
        mac: 4e:37:ab:b2:68:d7
        mtu: 1500
        name: enp4s0f0v3
        pciAddress: "0000:04:00.5"
        vendor: 15b3
        vfID: 3
      deviceID: "1017"
      driver: mlx5_core
      eSwitchMode: legacy
      linkSpeed: 25000 Mb/s
      linkType: ETH
      mac: 04:3f:72:d0:d2:b2
      mtu: 1500
      name: enp4s0f0np0
      numVfs: 4
      pciAddress: "0000:04:00.0"
      totalvfs: 4
      vendor: 15b3
    - Vfs:
      - deviceID: "1018"
        driver: mlx5_core
        mac: 3e:3a:7f:af:11:99
        mtu: 1500
        name: enp4s0f1v0
        pciAddress: "0000:04:00.6"
        vendor: 15b3
        vfID: 0
      - deviceID: "1018"
        driver: mlx5_core
        mac: 6e:c1:0e:52:ea:d8
        mtu: 1500
        name: enp4s0f1v1
        pciAddress: "0000:04:00.7"
        vendor: 15b3
        vfID: 1
      - deviceID: "1018"
        driver: mlx5_core
        mac: 8e:c8:1d:fc:69:0d
        mtu: 1500
        name: enp4s0f1v2
        pciAddress: "0000:04:01.0"
        vendor: 15b3
        vfID: 2
      - deviceID: "1018"
        driver: mlx5_core
        mac: 52:4c:5c:b1:1d:44
        mtu: 1500
        name: enp4s0f1v3
        pciAddress: "0000:04:01.1"
        vendor: 15b3
        vfID: 3
      deviceID: "1017"
      driver: mlx5_core
      eSwitchMode: legacy
      linkSpeed: 10000 Mb/s
      linkType: ETH
      mac: 04:3f:72:d0:d2:b3
      mtu: 1500
      name: enp4s0f1np1
      numVfs: 4
      pciAddress: "0000:04:00.1"
      totalvfs: 4
      vendor: 15b3
    syncStatus: Succeeded
kind: List
metadata:
  resourceVersion: ""
```

```
root@worker-node-1:~# cat /var/run/cdi/sriov-dp-spidernet.io.yaml
cdiVersion: 0.5.0
containerEdits: {}
devices:
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm6
      path: /dev/infiniband/issm6
      permissions: rw
    - hostPath: /dev/infiniband/umad6
      path: /dev/infiniband/umad6
      permissions: rw
    - hostPath: /dev/infiniband/uverbs6
      path: /dev/infiniband/uverbs6
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:04:00.6"
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm7
      path: /dev/infiniband/issm7
      permissions: rw
    - hostPath: /dev/infiniband/umad7
      path: /dev/infiniband/umad7
      permissions: rw
    - hostPath: /dev/infiniband/uverbs7
      path: /dev/infiniband/uverbs7
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:04:00.7"
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm8
      path: /dev/infiniband/issm8
      permissions: rw
    - hostPath: /dev/infiniband/umad8
      path: /dev/infiniband/umad8
      permissions: rw
    - hostPath: /dev/infiniband/uverbs8
      path: /dev/infiniband/uverbs8
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:04:01.0"
- containerEdits:
    deviceNodes:
    - hostPath: /dev/infiniband/issm9
      path: /dev/infiniband/issm9
      permissions: rw
    - hostPath: /dev/infiniband/umad9
      path: /dev/infiniband/umad9
      permissions: rw
    - hostPath: /dev/infiniband/uverbs9
      path: /dev/infiniband/uverbs9
      permissions: rw
    - hostPath: /dev/infiniband/rdma_cm
      path: /dev/infiniband/rdma_cm
      permissions: rw
  name: "0000:04:01.1"
kind: spidernet.io/net-pci
```

### Anything else we need to know?

https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/735

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<Input Version Here>|
|SR-IOV CNI Plugin            |<Input Version Here>|
|Multus                       |<Input Version Here>|
|Kubernetes                   |<Input Version Here>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.

### PR DESCRIPTION
**Pull request by souleb**
fixes #576 

This PR if implemented creates a `cdiSpec` file for each `resourcePool`. The file is removed first for each call to `CreateCDISpecForPool`. We calculate the digest of the `cdiSpec` to get a unique filename based on the `resourcePool` devices.

The manager itself makes sure to clean the directory in `initServers()` by calling `cleanupCDISpecs()` which will delete everything that matches `sriov-dp-*`

### CODE REVIEW

**Comment by souleb** [comment]
I have tested this with the following:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/rdma_resource1
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
---
souleb@c-237-115-20-025:~/network-operator$ cat pod-tc1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        nvidia.com/rdma_resource1: '1'
      limits:
        nvidia.com/rdma_resource1: '1'
```

I get the expected result:

```yaml
Name:             testpod1
Annotations:
                  k8s.v1.cni.cncf.io/networks: sriov-net1
                  k8s.v1.cni.cncf.io/networks-status:
                    [{
                        "name": "cilium",
                        "interface": "eth0",
                        "ips": [
                            "10.0.2.251"
                        ],
                        "mac": "9e:35:b3:cf:66:5e",
                        "default": true,
                        "dns": {}
                    },{
                        "name": "default/sriov-net1",
                        "interface": "net1",
                        "ips": [
                            "10.56.217.2"
                        ],
                        "mac": "ee:55:4d:84:c6:fa",
                        "dns": {},
                        "device-info": {
                            "type": "pci",
                            "version": "1.1.0",
                            "pci": {
                                "pci-address": "0000:b1:00.4",
                                "rdma-device": "mlx5_15"
                            }
                        }
                    }]
Status:           Running
```

One think to note though is the created files:

```shell
<>:/$ sudo ls -l /var/run/cdi
-rw------- 1 root root 3623 Aug  6 15:45 sriov-dp-nvidia.com-net-pci_104c6xxx.yaml
-rw------- 1 root root 1855 Aug  6 15:45 sriov-dp-nvidia.com-net-pci_71627xxx.yaml
```

The resources discovery order is not idempotent, so the filenames change overtime. I don't think this is an issue though.

File: pkg/cdi/cdi.go [hunk 1]
```diff
@@ -80,12 +84,26 @@ func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourceP
...
+		glog.Errorf("CreateCDISpecForPool(): can not calculate hash of the cdiSpec: %v", err)
+		return err
+	}
+	name, err := cdi.GenerateNameForTransientSpec(&cdiSpec, digest)
+	if err != nil {
+		glog.Errorf("CreateCDISpecForPool(): can not generate transient name: %v", err)
+		return err
+	}
+
+	err = cdi.GetRegistry().SpecDB().WriteSpec(&cdiSpec, cdiSpecPrefix+name)
```
Comment (adrianchiris) [inline pkg/cdi/cdi.go:99]: can we use  cdiSpecPrefix+ the pool name here ?

e.g :  `"sriov-dp-mellanox.com-rdma_resource_1"` 

that way we write the same file  then, no need to worry about c.lastGenratedName

Comment (souleb) [reply pkg/cdi/cdi.go:99]: I went with this to assure a unique name. There is no guarantee for the pool name to be unique right?

Comment (adrianchiris) [reply pkg/cdi/cdi.go:99]: we can assume that same as we assume no one else will create device plugin (unix) socket per resoruce. under kubelet dir (/var/lib/kubelet/plugins_registry/).

moreover for debuggability it would be better to understand which file belongs to which resource.

File: pkg/cdi/cdi.go [hunk 2]
```diff
@@ -39,6 +39,10 @@ type CDI interface {
 
 // impl implements CDI interface
 type impl struct {
+	// lastGeneratedName is the last computed file name to which the CDI spec
+	// was written. This is used to remove the spec file when the resource pool
+	// is removed or updated.
+	lastGeneratedName string
```
Comment (adrianchiris) [inline pkg/cdi/cdi.go:45]: do we need this now ?

File: pkg/cdi/cdi.go [hunk 3]
```diff
@@ -48,9 +52,9 @@ func New() CDI {
 
 // CreateCDISpecForPool creates CDI spec file with specified devices
 func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourcePool) error {
-	err := c.CleanupSpecs()
+	err := c.removeOldSpec()
```
Comment (adrianchiris) [inline pkg/cdi/cdi.go:55]: do we need this now ?

File: pkg/cdi/cdi.go [hunk 4]
```diff
@@ -80,12 +84,20 @@ func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourceP
 		cdiSpec.Devices = append(cdiSpec.Devices, device)
 	}
 
-	err = cdi.GetRegistry().SpecDB().WriteSpec(&cdiSpec, cdiSpecPrefix+resourcePrefix)
+	name, err := cdi.GenerateNameForSpec(&cdiSpec)
+	if err != nil {
+		glog.Errorf("CreateCDISpecForPool(): can not generate transient name: %v", err)
```
Comment (adrianchiris) [inline pkg/cdi/cdi.go:89]: nit: remove "transient"

File: pkg/cdi/cdi.go [hunk 5]
```diff
@@ -80,12 +84,20 @@ func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourceP
...
+		return err
+	}
+
+	err = cdi.GetRegistry().SpecDB().WriteSpec(&cdiSpec, cdiSpecPrefix+name+"-"+rPool.GetResourceName())
```
Comment (adrianchiris) [inline pkg/cdi/cdi.go:93]: cant we use : `strings.Join("-", cdiSpecPrefix, resourcePrefix, rPool.GetResourceName)` as name ?

File: pkg/cdi/cdi.go (hunk 2 above)
Comment (souleb) [reply pkg/cdi/cdi.go:45]: We create a single file per `resourcePool`. We have to remember that a file has been created, or we need to check if the file exist. First option is fatser.

File: pkg/cdi/cdi.go (hunk 5 above)
Comment (souleb) [reply pkg/cdi/cdi.go:93]: I don't really have a preference. My thought was that it's best to use cdi provided helper, as we use it already to write the spec to file.

File: pkg/cdi/cdi.go (hunk 2 above)
Comment (adrianchiris) [reply pkg/cdi/cdi.go:45]: its now going to have the same name, writeSpec will replace the file.
so i dont understand now why we need this bit.

Comment (souleb) [reply pkg/cdi/cdi.go:45]: If a write fails, we will keep around the old file... It should be deleted first, so we don't keep around irrelevant data right?

Comment (adrianchiris) [reply pkg/cdi/cdi.go:45]: if write fails, how likely it is for delete to succeed ?
if delete fails, we keep around outdated information right ? so it just moves the possible issue around.

perhaps if CreateCDISpecForPool fails we should fail device plugin altogether.

File: pkg/cdi/cdi.go (hunk 5 above)
Comment (adrianchiris) [reply pkg/cdi/cdi.go:93]: ack, your call.

**Review by adrianchiris — APPROVED** [review]
LGTM!  thx @souleb appreciate your patience :)

File: pkg/cdi/cdi.go [hunk 6]
```diff
@@ -48,11 +48,6 @@ func New() CDI {
 
 // CreateCDISpecForPool creates CDI spec file with specified devices
 func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourcePool) error {
-	err := c.CleanupSpecs()
```
[the remark this answers is not in the document]
Comment (adrianchiris) [reply pkg/cdi/cdi.go:51]: all CDI files prefixed with "sriov-dp" are deleted on device plugin start. (existing logic)

File: pkg/cdi/cdi.go [hunk 7]
```diff
@@ -80,7 +75,14 @@ func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourceP
 		cdiSpec.Devices = append(cdiSpec.Devices, device)
 	}
 
-	err = cdi.GetRegistry().SpecDB().WriteSpec(&cdiSpec, cdiSpecPrefix+resourcePrefix)
+	name, err := cdi.GenerateNameForSpec(&cdiSpec)
+	if err != nil {
+		glog.Errorf("CreateCDISpecForPool(): can not generate name: %v", err)
```
Comment (Eoghan1232) [inline pkg/cdi/cdi.go:80]:
```suggestion
		glog.Errorf("GenerateNameForSpec(): can not generate name: %v", err)
```

should it be like this?

File: pkg/cdi/cdi.go [hunk 8]
```diff
@@ -80,7 +75,14 @@ func (c *impl) CreateCDISpecForPool(resourcePrefix string, rPool types.ResourceP
...
+		return err
+	}
+
+	// this will overwrite any existing file for this spec with the same name
+	err = cdi.GetRegistry().SpecDB().WriteSpec(&cdiSpec, cdiSpecPrefix+name+"-"+rPool.GetResourceName())
```
[the remark this answers is not in the document]
Comment (Eoghan1232) [reply pkg/cdi/cdi.go:85]: +1 ^

**Review by Eoghan1232 — APPROVED** [review]

**Comment by adrianchiris** [comment]
merging this one ! @souleb appreciate the patience
