### PR TITLE
bug: rdma exlusive handling

### LINKED ISSUE #565: Capacity and Allocatable number shows wrong if sriov-network-device-plugin restarts
### What happened?
Node `Capacity` and `Allocatable` number shows wrong in case of restarting `sriov-network-device-plugin` if any pods attach SR-IOV IB VFs.

* Before restarts
```
Capacity:
  .....
  openshift.io/gpu_mlnx_ib0:  8
  openshift.io/gpu_mlnx_ib1:  8
  openshift.io/gpu_mlnx_ib2:  8
  openshift.io/gpu_mlnx_ib3:  8
  openshift.io/gpu_mlnx_ib4:  8
Allocatable:
  .....
  openshift.io/gpu_mlnx_ib0:  8
  openshift.io/gpu_mlnx_ib1:  8
  openshift.io/gpu_mlnx_ib2:  8
  openshift.io/gpu_mlnx_ib3:  8
  openshift.io/gpu_mlnx_ib4:  8
```
* After restarts
```
Capacity:
  openshift.io/gpu_mlnx_ib0:  2
  openshift.io/gpu_mlnx_ib1:  2
  openshift.io/gpu_mlnx_ib2:  2
  openshift.io/gpu_mlnx_ib3:  2
  openshift.io/gpu_mlnx_ib4:  2
Allocatable:
  openshift.io/gpu_mlnx_ib0:  2
  openshift.io/gpu_mlnx_ib1:  2
  openshift.io/gpu_mlnx_ib2:  2
  openshift.io/gpu_mlnx_ib3:  2
  openshift.io/gpu_mlnx_ib4:  2
```

### What did you expect to happen?
`openshift.io/gpu_mlnx_ib#` should be 8 in all VFs.

### What are the minimal steps needed to reproduce the bug?
1. Deploy `sriov-network-operator` version v1.2.0
2. Create a Pod or Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sriov-testing-deployment-h100
spec:
  replicas: 6
  selector:
    matchLabels:
      app: sriov-testing-h100
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name": "sriov-gpu2-ib0", "interface": "net1"},
          {"name": "sriov-gpu2-ib1", "interface": "net2"}, {"name": "sriov-gpu2-ib2",
          "interface": "net3"}, {"name": "sriov-gpu2-ib3", "interface": "net4"}, {"name":
          "sriov-gpu2-ib4", "interface": "net5"}]'
      labels:
        app: sriov-testing-h100
      name: sriov-testing-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - sleep inf
        image: mellanox/tcpdump-rdma:latest
        imagePullPolicy: Always
        name: tcpdump-rdma
        resources:
          limits:
            openshift.io/gpu2_mlnx_ib0: "1"
            openshift.io/gpu2_mlnx_ib1: "1"
            openshift.io/gpu2_mlnx_ib2: "1"
            openshift.io/gpu2_mlnx_ib3: "1"
            openshift.io/gpu2_mlnx_ib4: "1"
          requests:
            openshift.io/gpu2_mlnx_ib0: "1"
            openshift.io/gpu2_mlnx_ib1: "1"
            openshift.io/gpu2_mlnx_ib2: "1"
            openshift.io/gpu2_mlnx_ib3: "1"
            openshift.io/gpu2_mlnx_ib4: "1"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
```
3. Rollout `sriov-device-plugin` daemonset
```
k rollout restart -n sriov-network-operator daemonset.apps/sriov-device-plugin
```
4. Check whether `Capacity` and `Allocatable` shows full capacity or not

### Anything else we need to know?
There were several issues already raised and commits were pushed, but it seems that this issue won't be fixed yet.
xref) https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/276, https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/521

After restaring `sriov-device-plugin`, `kubelet` says that `sriov-device-plugin` pushed its state like below:
```
kubelet[1223475]: I0605 16:48:30.294908 1223475 manager.go:229] "Device plugin connected" resourceName="openshift.io/gpu_mlnx_ib0"
kubelet[1223475]: I0605 16:48:30.295508 1223475 client.go:91] "State pushed for device plugin" resource="openshift.io/gpu_mlnx_ib0" resourceCapacity=2
kubelet[1223475]: I0605 16:48:30.295721 1223475 http2_client.go:959] "[transport] [client-transport 0xc004920000] Closing: connection error: desc = \"error reading from server: read unix @->/var/lib/kubelet/plugins_registry/openshift.io_gpu_mlnx_ib0.sock: use of closed network connection\"\n"
kubelet[1223475]: I0605 16:48:30.298096 1223475 manager.go:278] "Processed device updates for resource" resourceName="openshift.io/gpu_mlnx_ib0" totalCount=2 healthyCount=2
```
Even if I changed image version of all components to `latest`, but this issue still occurs.

I'm using A100 and H100 nodes.

### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |latest (I've also tested v3.5.1 and v3.7.0)|
|SR-IOV CNI Plugin            |latest (I've also tested `sriovCni`: v2.6.3 and `ibSriovCni`: v1.0.2)|
|Multus                       |v3.8|
|Kubernetes                   |v1.21.6, v1.28.3| 
|OS                           |ubuntu 20.04, 22.04|

### Config Files
Config file locations may be config dependent.

### PR DESCRIPTION
**Pull request by rollandf**
In case a RDMA device in exclusive mode is in use by a Pod, the DP was not reporting it as a resource after DP restart.

Following changes are introduced in RdmaSpec:

- isRdma: in case of no rdma resources, check if netlink "enable_rdma" is available.
- GetRdmaDeviceSpec: the device specs are retrieved dynamically and not on discovery stage as before.

Dynamic RDMA specs computation vs on discovery, comes to solve following scenario for exlusive mode:
- Discover RDMA device
- Allocate to Pod (resources are hidden on host)
- Restart DP pod
- Discovery
- Deallocate
- Reallocate

Fixes #565

### CODE REVIEW

**Comment by rollandf** [comment]
@SchSeba @zeeke PTAL

**Review by ykulazhenkov — APPROVED** [review]

**Review by e0ne — APPROVED** [review]

**Review by almaslennikov — APPROVED** [review]

File: pkg/utils/netlink_provider.go [hunk 1]
```diff
@@ -48,6 +50,19 @@ func GetNetlinkProvider() NetlinkProvider {
...
+// equivalent to "devlink dev param show pci/0000:d8:01.1 name enable_rdma"
+func (defaultNetlinkProvider) HasRdmaParam(pciAddr string) (bool, error) {
+	param, err := nl.DevlinkGetDeviceParamByName("pci", pciAddr, "enable_rdma")
+	if err != nil {
+		return false, fmt.Errorf("error getting enable_rdma attribute for pci device %s %v", pciAddr, err)
+	}
+	if len(param.Values) == 0 || param.Values[0].Data == nil {
+		return false, nil
+	}
+	return true, nil
```
Comment (adrianchiris) [inline pkg/utils/netlink_provider.go:63]: is there a case where enable_rdma parameter value has data which interprets to "false" ?

File: pkg/devices/rdma_test.go [hunk 2]
```diff
@@ -31,16 +32,32 @@ var _ = Describe("RdmaSpec", func() {
 	Describe("creating new RdmaSpec", func() {
 		t := GinkgoT()
 		Context("successfully", func() {
-			It("without device specs", func() {
+			It("without device specs, without netlik enable_rdma param", func() {
```
Comment (adrianchiris) [inline pkg/devices/rdma_test.go:35]: nit: netlik -> netlink

File: pkg/devices/rdma_test.go [hunk 3]
```diff
@@ -31,16 +32,32 @@ var _ = Describe("RdmaSpec", func() {
...
 				fakeRdmaProvider.On("GetRdmaDevicesForPcidev", "0000:00:00.0").Return([]string{})
 				utils.SetRdmaProviderInst(&fakeRdmaProvider)
-				spec := devices.NewRdmaSpec("0000:00:00.0")
+				spec := devices.NewRdmaSpec(types.NetDeviceType, "0000:00:00.0")
 
 				Expect(spec.IsRdma()).To(BeFalse())
 				Expect(spec.GetRdmaDeviceSpec()).To(HaveLen(0))
 				fakeRdmaProvider.AssertExpectations(t)
 			})
+			It("without device specs, with netlik enable_rdma param", func() {
```
Comment (adrianchiris) [inline pkg/devices/rdma_test.go:48]: nit: same as above.

File: pkg/utils/netlink_provider.go [hunk 4]
```diff
@@ -48,6 +50,19 @@ func GetNetlinkProvider() NetlinkProvider {
 	return netlinkProvider
 }
 
+// HasRdmaParam returns true if PCI device has "enable_rdma" param
+// equivalent to "devlink dev param show pci/0000:d8:01.1 name enable_rdma"
+func (defaultNetlinkProvider) HasRdmaParam(pciAddr string) (bool, error) {
+	param, err := nl.DevlinkGetDeviceParamByName("pci", pciAddr, "enable_rdma")
```
Comment (adrianchiris) [inline pkg/utils/netlink_provider.go:56]: this will not work for devices on auxiliary bus. (in case of SFs which are supported by device plugin)

File: pkg/utils/utils.go [hunk 5]
```diff
@@ -474,6 +474,15 @@ func GetPfEswitchMode(pciAddr string) (string, error) {
 	return devLinkDeviceAttrs.Mode, nil
 }
 
+// HasRdmaParam returns true if PCI device has "enable_rdma" param
+func HasRdmaParam(pciAddr string) (bool, error) {
```
Comment (adrianchiris) [inline pkg/utils/utils.go:478]: this is called by rdmaSpec with deviceID which is either pci address or Auxiliary device name.

we should support both or add a new func that handles auxiliary devices

File: pkg/utils/netlink_provider.go (hunk 1 above)
Comment (rollandf) [reply pkg/utils/netlink_provider.go]: Returning the value of the param now.

File: pkg/devices/rdma_test.go (hunk 2 above)
Comment (rollandf) [reply pkg/devices/rdma_test.go]: Done

File: pkg/devices/rdma_test.go (hunk 3 above)
Comment (rollandf) [reply pkg/devices/rdma_test.go]: Done

File: pkg/utils/netlink_provider.go (hunk 4 above)
Comment (rollandf) [reply pkg/utils/netlink_provider.go]: Fixed

File: pkg/utils/utils.go (hunk 5 above)
Comment (rollandf) [reply pkg/utils/utils.go]: Updated to support both

File: pkg/utils/utils.go [hunk 6]
```diff
@@ -474,6 +474,15 @@ func GetPfEswitchMode(pciAddr string) (string, error) {
 	return devLinkDeviceAttrs.Mode, nil
 }
 
+// HasRdmaParam returns true if device has "enable_rdma" param
+func HasRdmaParam(bus, pciAddr string) (bool, error) {
```
Comment (adrianchiris) [inline pkg/utils/utils.go:478]: nit: pciAddr -> device
also add some info in comment about expected format of the device depending on the bus

File: pkg/devices/rdma_test.go [hunk 7]
```diff
@@ -31,16 +32,32 @@ var _ = Describe("RdmaSpec", func() {
 	Describe("creating new RdmaSpec", func() {
 		t := GinkgoT()
 		Context("successfully", func() {
-			It("without device specs", func() {
+			It("without device specs, without netlink enable_rdma param", func() {
```
[the remark this answers is not in the document]
Comment (rollandf) [reply pkg/devices/rdma_test.go:35]: Done

File: pkg/utils/utils.go (hunk 6 above)
Comment (rollandf) [reply pkg/utils/utils.go]: Done

File: pkg/devices/rdma.go [hunk 8]
```diff
@@ -18,22 +18,65 @@
...
+	//nolint: exhaustive
+	switch r.deviceType {
+	case types.NetDeviceType:
+		bus = "pci"
+	case types.AuxNetDeviceType:
+		bus = "auxiliary"
+	default:
+		return false
+	}
+	// Checking for netlink param for exclusive RDMA use case
```
Comment (adrianchiris) [inline pkg/devices/rdma.go:55]: can you add more information here why we need to check netlink param in this case. (requested by sebastian)

**Review by adrianchiris — APPROVED** [review]

**Comment by rollandf** [comment]
@SchSeba can you PTAL?

**Review by SchSeba — APPROVED** [review]
I tested this one and also add a functional test to cover this one in the operator https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/799/files#diff-909069834ea269a01a51f28b8830efebec16799766767ebcd01b58f966ddc5c5R226 (real mlx device is needed for the test to run)
